version: '3.1'

# Currently we only let the host visit 9001, which is the supervisor web console
# Note that the ports under the 'expose' section have no actual effect.

# The inner nginx only listen to 80, and should be forwarded to with 'exp:80'
# from another container within the same 'backbone' network
# 80 is not accessible directly from outside

services:
  exp: 
    build: .
    volumes:
      - .:/app
      - ./notebooks:/tf/notebooks      
      - ./tron_nginx.conf:/etc/nginx/conf.d/tron_nginx.conf
    ports:
      - 9001:9001
    networks:
      - backbone
    expose:
      - "80"
      - "9001"
 
networks:
  backbone:
    external:
      name: backbone