version: '3.1'

# Currently we only let the host visit 9001, which is the supervisor web console
# Note that the ports under the 'expose' section have no actual effect.

# The inner nginx only listen to 8080, and should be forwarded to with 'exp:8080'
# from another container within the same 'backbone' network
# 8080 is not accessible directly from outside

services:
  exp: 
    build: .
    volumes:
      - .:/app
      - ./notebooks:/tf/notebooks      
      - ./tron_nginx.conf:/etc/nginx/conf.d/tron_nginx.conf
    ports:
      - 9001:9001
    networks:
      - backbone
    expose:
      - "8080"
      - "9001"
 
networks:
  backbone:
    external:
      name: backbone